#!/bin/sh
I4J_INSTALL_LOCATION="/opt/Spark"
cd "$I4J_INSTALL_LOCATION"
if [ "$1" = "configure" ]; then
ln -sf "$I4J_INSTALL_LOCATION/Spark" /usr/local/bin/
/bin/echo -e "#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=Spark
Exec=/bin/sh \"$I4J_INSTALL_LOCATION/Spark\" %U
StartupWMClass=install4j-org-jivesoftware-launcher-Startup
Icon=$I4J_INSTALL_LOCATION/.install4j/Spark.png
" > "$I4J_INSTALL_LOCATION/.install4j/install4j_1srd41-Spark.desktop"
xdg-desktop-menu install --mode system "$I4J_INSTALL_LOCATION/.install4j/install4j_1srd41-Spark.desktop" 2>/dev/null
cp "$I4J_INSTALL_LOCATION/.install4j/install4j_1srd41-Spark.desktop" "$I4J_INSTALL_LOCATION/Spark.desktop"
chmod +x "$I4J_INSTALL_LOCATION/Spark.desktop"
ln -sf "$I4J_INSTALL_LOCATION/starter" /usr/local/bin/
/bin/echo -e "#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=starter
Exec=/bin/sh \"$I4J_INSTALL_LOCATION/starter\" %U
StartupWMClass=install4j-org-jivesoftware-Restarter
" > "$I4J_INSTALL_LOCATION/.install4j/install4j_1srd41-starter.desktop"
xdg-desktop-menu install --mode system "$I4J_INSTALL_LOCATION/.install4j/install4j_1srd41-starter.desktop" 2>/dev/null
cp "$I4J_INSTALL_LOCATION/.install4j/install4j_1srd41-starter.desktop" "$I4J_INSTALL_LOCATION/starter.desktop"
chmod +x "$I4J_INSTALL_LOCATION/starter.desktop"

if [ -d "$I4J_INSTALL_LOCATION/jre/lib" ]; then
  old_pwd200=`pwd`
  cd "$I4J_INSTALL_LOCATION/jre"
  for pack_file in lib/*.jar.pack
  do
    if [ -f "$pack_file" ]; then
      jar_file=`echo "$pack_file" | awk '{ print substr($0,1,length($0)-5) }'`
      bin/unpack200 -r "$pack_file" "$jar_file" > /dev/null 2>&1
    fi
  done
  for pack_file in lib/ext/*.jar.pack
  do
    if [ -f "$pack_file" ]; then
      jar_file=`echo "$pack_file" | awk '{ print substr($0,1,length($0)-5) }'`
      bin/unpack200 -r "$pack_file" "$jar_file" > /dev/null 2>&1
    fi
  done
  bin/java -Xshare:dump >/dev/null 2>&1
  cd "$old_pwd200"
fi

fi
exit 0
